wimdeblauwe/htmx-spring-boot

- .gitignore
Just a helper for the asdf tool to ensure I use the proper Java version when in this directory.
> Add asdf to .gitignore to ensure local java version properly

- readme.md
- Fixed indentation in code samples
- Wrapped lines following the recommended practice for prose in version-controlled systems:
<https://rhodesmill.org/brandon/2012/one-sentence-per-line/>
- Normalized markup for unordered lists
- Removed unused blank line in code samples
> README: whitespace adjustments

- readme.md
A the moment it will link to https://github.com/wimdeblauwe/htmx-spring-boot-thymeleaf/blob/main/www.htmx.org
> Fix link to https://htmx.org/ in readme

- src/main/java/io/github/wimdeblauwe/hsbt/mvc/HtmxMvcConfiguration.java
- src/main/java/io/github/wimdeblauwe/hsbt/mvc/HtmxPartials.java
- src/main/java/io/github/wimdeblauwe/hsbt/mvc/HtmxViewHandlerInterceptor.java
Introduce HtmxPartials to provide a convenient API for controller methods to specify Thymeleaf fragments to be rendered to ultimately trigger different parts of the page updated. The abstraction is handled in a custom HandlerInterceptor that renders a view that triggers the rendering of the registered fragments individually.
I've stripped down a lot of stuff from what I previously had in [Spring Playground](https://github.com/odrotbohm/spring-playground/tree/main/htmx-spring-boot). The server sent events support is completely gone for now as that allows a significantly simplified arrangement and less abstractions to introduce. Feel free to massage as you see fit.
> Add support for HTMX partials.

- src/main/java/io/github/wimdeblauwe/hsbt/mvc/HtmxHandlerInterceptor.java
- src/main/java/io/github/wimdeblauwe/hsbt/mvc/HtmxResponseHeader.java
- src/main/java/io/github/wimdeblauwe/hsbt/mvc/HtmxViewHandlerInterceptor.java
> Add all constants to HtmxResponseHeader

- README.md
Fixed typos from hx-swap-oop to hx-swap-oob in RAEDME.md
> Fixed typos from hx-swap-oop to hx-swap-oob

- src/main/java/io/github/wimdeblauwe/hsbt/mvc/HtmxHandlerMethodArgumentResolver.java
- Removed System.out.println() from HtmxHandlerMethodArgumentResolver
- Removed unwanted object of native request
fixes: #47
> println() method removed from HtmxHandlerMethodArgumentResolver

- src/main/java/io/github/wimdeblauwe/hsbt/mvc/HtmxResponse.java
- src/test/java/io/github/wimdeblauwe/hsbt/mvc/HtmxResponseTest.java
> 48: preserve the order of templates inside the HtmxResponse

- src/main/java/io/github/wimdeblauwe/hsbt/mvc/HtmxHandlerInterceptor.java
- src/main/java/io/github/wimdeblauwe/hsbt/mvc/HtmxMvcConfiguration.java
- src/test/java/io/github/wimdeblauwe/hsbt/DummyApplication.java
- src/test/java/io/github/wimdeblauwe/hsbt/mvc/HxGetMapping.java
Alternative implementation of #41
> Use well-known bean name for view resolver

- src/main/java/io/github/wimdeblauwe/hsbt/mvc/HtmxViewHandlerInterceptor.java
Some `View` implementations will (not unreasonably) call `response.getWriter()` and write content directly. This is an error (in the spec I think) and Tomcat, for example, will barf. You can dodge the bullet by using an existing mechanism in Spring.
> Use caching response wrapper in case views render pre-emptively

- README.md
- src/main/java/io/github/wimdeblauwe/hsbt/mvc/HtmxMvcConfiguration.java
- src/main/java/io/github/wimdeblauwe/hsbt/mvc/HtmxResponse.java
- src/main/java/io/github/wimdeblauwe/hsbt/mvc/HtmxViewHandlerInterceptor.java
- src/test/java/io/github/wimdeblauwe/hsbt/mvc/HtmxPartialHandlerInterceptorTest.java
- src/test/java/io/github/wimdeblauwe/hsbt/mvc/HtmxResponseTest.java
- src/test/java/io/github/wimdeblauwe/hsbt/mvc/PartialsController.java
Also as fully-formed `ModelAndView`, or (as before) as view name `String` to be resolved later.
See https://github.com/wimdeblauwe/htmx-spring-boot-thymeleaf/discussions/53
> Allow templates to be added as resolved Views

- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponse.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponseTest.java
> [fix] retarget property not overridden in HtmxResponse#and method

- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponse.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponseHeader.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxViewHandlerInterceptor.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxViewHandlerInterceptorController.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxViewHandlerInterceptorTest.java
Instead of passing `"false"` to `HtmxResponse.Builder#pushUrl` or `HtmxResponse.Builder#replaceUrl`, a new convenience method `preventHistoryUpdate()` has been added. Since htmx only considers one of the headers `HX-Push-Url` or `HX-Replace-Url`, and in exactly that order, it was obvious to offer such a method.
> Add support for HX-Replace-Url response header in HtmxResponse

- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponse.java
Since the builder of `HtmxResponse` is not yet part of a release, I could have safely removed this method and not marked it as deprecated.
> No need to mark HtmxResponse.Builder#reswap as deprecated because it was not part of a release

- README.md
> Fix javadoc.io links in README.md

- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/security/HxRefreshHeaderAuthenticationEntryPoint.java
For some reason that I haven't figured out, the authentication entrypoint is called twice for me whenever a user isn't logged. Since the entrypoint uses `addHeader()` it will result in two `HX-Refresh` headers in the response, making htmx ignore the header.
Even though there's probably something wrong with my code, changing it to use `setHeader()` will work around this and make sure there is only one `HX-Refresh` header in the response, making htmx behave as it should.
And thank you for a great library!
> Use setHeader() instead of addHeader() to avoid multiple headers being set

- htmx-spring-boot/pom.xml
This warning is caused by the javax.annotation.meta.When enum not being available to the runtime and org.springframework.lang.Nullable references this enum but it is not made available automatically.
> [fix] warning: unknown enum constant When.MAYBE caused by missing JSR305 implementation

- pom.xml
Silencing the maven-javadoc plugin.
```
[WARNING] Javadoc Warnings
[WARNING] /htmx-spring-boot/htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerInterceptor.java:17: warning: no comment
[WARNING] public class HtmxHandlerInterceptor implements HandlerInterceptor {
[WARNING] ^
[WARNING] /htmx-spring-boot/htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerMethodArgumentResolver.java:14: warning: no comment
[WARNING] public class HtmxHandlerMethodArgumentResolver implements HandlerMethodArgumentResolver {
[WARNING] ^
[WARNING] /htmx-spring-boot/htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerMethodArgumentResolver.java:28: warning: no comment
[WARNING] public static HtmxRequest …
```
> [maven-javadoc-plugin] disable missing warnings

- pom.xml
As mentioned on [Issue](https://github.com/wimdeblauwe/htmx-spring-boot/issues/112) the spring-asciidoctor-backends is now available on maven central so there is no need to keep the plugin repository.  So I have removed it from pom.xml.
> Remove spring plugin repository 

- README.md
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerInterceptor.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxMvcAutoConfiguration.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxValue.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxLocation.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxPushUrl.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxRedirect.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxReplaceUrl.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxReselect.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxReswap.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxRetarget.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxTriggerAfterSettle.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxTriggerAfterSwap.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxTriggerLifecycle.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerInterceptorTest.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/TestController.java
This will add the missing annotations for all available response headers.
Superseded #117.
> Add missing annotations for response headers

- htmx-spring-boot-thymeleaf/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/thymeleaf/HtmxThymeleafAutoConfiguration.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxMvcAutoConfiguration.java
Due to the fact that a user can customize the Jackson ObjectMapper bean (e.g. `spring.jackson.serialization.indent-output=true`) in Spring Boot, this leads to unwanted errors when it comes to serializing. Therefore, we no longer rely on this ObjectMapper.
Fixes #57
> [fix] Invalid characters (CR/LF) in response header caused by customized Jackson ObjectMapper

- README.md
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerInterceptor.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxMvcAutoConfiguration.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponseHandlerMethodArgumentResolver.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponseHandlerMethodReturnValueHandler.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponseHandlerMethodReturnValueHandlerController.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponseHandlerMethodReturnValueHandlerTest.java
Addresses #127 
This enables the following usecase:
```kotlin
@GetMapping("/admin")
fun getAdmin(htmxResponse: HtmxResponse.Builder): JteModel {
htmxResponse.trigger("aTrigger")
return templates.adminIndex("Hello")
}
```
The `JteModel` is a typed template. But the `HtmxResponse` can be used as an argument to inform any triggers, redirect, etc. that need to happen. 
This change also supports adding `HtmxReponse` to the model and being processed, if that approach is needed.
> Add support for processing HtmxResponse in the Model and as an Argument

- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerInterceptor.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxReplaceUrl.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerInterceptorTest.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/TestController.java
When using `@HxPushUrl` without a value it pushes `true` in the url, instead of the fetched URL
Now the path gets retreived from the request.
> @HxPushUrl(true) now retreives the path from the request

- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerInterceptor.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponseHandlerMethodReturnValueHandler.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponseHandlerMethodReturnValueHandlerController.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponseHandlerMethodReturnValueHandlerTest.java
This adds handling for [flash attributes](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-methods/flash-attributes.html) via `RedirectAttributes`. Now you can perform client-side redirects with htmx and the flash attributes work as with normal redirects.
Fixes #96
> Handle flash attributes on htmx redirects

- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerInterceptor.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponse.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponseHandlerMethodReturnValueHandler.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxLocation.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxPushUrl.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxRedirect.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxReplaceUrl.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/RequestContextUtils.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerInterceptorTest.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxResponseHandlerMethodReturnValueHandlerTest.java
I have noticed that URLs that can be set in htmx response headers e.g. `HX-Redirect` are not automatically interpreted as context relative. This is a bit annoying because you have to manually prepend the context path in your controller method. And that's why I've changed this behavior. Each URL starts with a slash ("/") is interpreted as context relative to the current ServletContext and therefore the context path will be prepended to the URL.
It is also possible to deactivate this behavior in the `HtmxResponse.Builder` and in all relevant annotations e.g `@HxRedirect` etc.
> Prepend context path to context relative URLs in htmx response headers

- README.md
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxViewResolver.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerMethodTest.java
To solve this issue, the special view name prefixes must be changed from `htmx:redirect:/path`, `htmx:location:/path` to `redirect:htmx:/path`, `redirect:htmx:location:/path`.
Fixes #144
> [fix] string-based redirections with flash attributes not working

- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxExceptionHandlerExceptionResolver.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerInterceptor.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerMethodAnnotationHandler.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxMvcAutoConfiguration.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxHandlerMethodTest.java
> [fix] Annotations on exception handler methods do not work

- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxRequestMappingHandlerMapping.java
- htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HxRequest.java
- htmx-spring-boot/src/test/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxRequestMappingHandlerMappingTest.java
This adds a new annotation parameter `historyRestoreRequest` to `@HxRequest` to control whether the mapping should be applied to requests made for History Restore Requests.
By default, the mapping is not applied to history restore requests.
Resolves #170.
> Allow @HxRequest to ignore restore history requests and ignore them by default
